<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunMunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currentDateTime = date('Y-m-d H:i:s');
        $municipalities = array(
            //AHUACHAPAN
            ['mun_nombre' => 'Ahuachapán', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Apaneca', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Atiquizaya', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Concepción de Ataco', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Refugio', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Guaymango', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jujutla', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Menéndez', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Lorenzo', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Pedro Puxtla', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tacuba', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Turín', 'mun_id_dep' => 1, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //SANTA ANA
            ['mun_nombre' => 'Santa Ana', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Candelaria de la Frontera', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chalchuapa', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Coatepeque', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Congo', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Porvenir', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Masahuat', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio Pajonal', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Sebastián Salitrillo', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Rosa Guachipilín', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santiago de la Frontera', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Texistepeque', 'mun_id_dep' => 2, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //SONSONATE
            ['mun_nombre' => 'Sonsonate', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Acajutla', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Armenia', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Caluco', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Cuisnahuat', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Izalco', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Juayúa', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nahuizalco', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nahulingo', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Salcoatitán', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio del Monte', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Julián', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Catarina Masahuat', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Isabel Ishuatán', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santo Domingo de Guzmán', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Sonzacate', 'mun_id_dep' => 3, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //CHALATENANGO
            ['mun_nombre' => 'Agua Caliente', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Arcatao', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Azacualpa', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Citalá', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Comalapa', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Concepción Quezaltepeque', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Dulce Nombre de María', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Carrizal', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Paraíso', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'La Laguna', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'La Palma', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'La Reina', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Las Vueltas', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nueva Concepción', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nueva Trinidad', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nombre de Jesús', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ojos de Agua', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Potonico', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio de la Cruz', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio Los Ranchos', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Fernando', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Lempa', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Morazán', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Ignacio', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Isidro Labrador', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San José Cancasque', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San José Las Flores', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Luis del Carmen', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Miguel de Mercedes', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Rafael', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Rita', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tejutla', 'mun_id_dep' => 4, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //CUSCATLAN
            ['mun_nombre' => 'Candelaria', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Cojutepeque', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Carmen', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Rosario', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Monte San Juan', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Oratorio de Concepción', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Bartolomé Perulapía', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Cristóbal', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San José Guayabal', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Pedro Perulapán', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Rafael Cedros', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Ramón', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Cruz Analquito', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Cruz Michapa', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Suchitoto', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tenancingo', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Victoria', 'mun_id_dep' => 5, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //LA LIBERTAD
            ['mun_nombre' => 'Antiguo Cuscatlán', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chiltiupán', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ciudad Arce', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Colón', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Comasagua', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Huizúcar', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jayaque', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jicalapa', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'La Libertad', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nuevo Cuscatlán', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San José Villanueva', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Matías', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Pablo Tacachico', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Talnique', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tamanique', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Teotepeque', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tepecoyo', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Zaragoza', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //LA PAZ
            ['mun_nombre' => 'Cuyultitán', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Rosario', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jerusalén', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Mercedes La Ceiba', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Olocuilta', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Paraíso de Osorio', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio Masahuat', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Emigdio', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Chinameca', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Juan Nonualco', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Juan Talpa', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Juan Tepezontes', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Luis La Herradura', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Luis Talpa', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Miguel Tepezontes', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Pedro Masahuat', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Pedro Nonualco', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Rafael Obrajuelo', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa María Ostuma', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santiago Nonualco', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tapalhuaca', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Zacatecoluca', 'mun_id_dep' => 7, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //LA UNION
            ['mun_nombre' => 'Anamorós', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Bolívar', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Concepción de Oriente', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Conchagua', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Carmen', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Sauce', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Intipucá', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'La Unión', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Lislique', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Meanguera del Golfo', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nueva Esparta', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Pasaquina', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Polorós', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Alejo', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San José', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Rosa de Lima', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Yayantique', 'mun_id_dep' => 8, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Yucuaiquín', 'mun_id_dep' => 6, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //MORAZAN
            ['mun_nombre' => 'Arambala', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Cacaopera', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chilanga', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Corinto', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Delicias de Concepción', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Divisadero', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Rosario', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Gualococti', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Guatajiagua', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jocoaitique', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jocoro', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Lolotiquillo', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Meanguera', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Osicala', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Perquín', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Carlos', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Fernando', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Gotera', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Isidro', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Simón', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Sensembra', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Yamabal', 'mun_id_dep' => 9, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //SAN MIGUEL
            ['mun_nombre' => 'Carolina', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chapeltique', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chinameca', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Chirilagua', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ciudad Barrios', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Comacarán', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Tránsito', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Lolotique', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Moncagua', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nueva Guadalupe', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nuevo Edén de San Juan', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Quelepa', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Antonio del Mosco', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Gerardo', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Jorge', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Luis de la Reina', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Miguel', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Rafael Oriente', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Sesori', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Uluazapa', 'mun_id_dep' => 10, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //SAN SALVADOR
            ['mun_nombre' => 'Aguilares', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Apopa', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ayutuxtepeque', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Cuscatancingo', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Delgado', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Paisnal', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Guazapa', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ilopango', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Mejicanos', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nejapa', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Panchimalco', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Rosario de Mora', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Marcos', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Martín', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Salvador', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santiago Texacuangos', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santo Tomás', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Soyapango', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tonacatepeque', 'mun_id_dep' => 11, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //SAN VICENTE
            ['mun_nombre' => 'Apastepeque', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Guadalupe', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Cayetano Istepeque', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Esteban Catarina', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Ildefonso', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Lorenzo', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Sebastián', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Vicente', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Clara', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santo Domingo', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tecoluca', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tepetitán', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Verapaz', 'mun_id_dep' => 12, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //CABAÑAS
            ['mun_nombre' => 'Cinquera', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Dolores', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Guacotecti', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ilobasco', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jutiapa', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Isidro', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Sensuntepeque', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tejutepeque', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Victoria', 'mun_id_dep' => 13, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],

            //USULUTÁN
            ['mun_nombre' => 'Alegría', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Berlín', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'California', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Concepción Batres', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'El Triunfo', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ereguayquín', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Estanzuelas', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jiquilisco', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jucuapa', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Jucuarán', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Mercedes Umaña', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Nueva Granada', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Ozatlán', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Puerto El Triunfo', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Agustín', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Buenaventura', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Dionisio', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'San Francisco Javier', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa Elena', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santa María', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Santiago de María', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Tecapán', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime],
            ['mun_nombre' => 'Usulután', 'mun_id_dep' => 14, 'mun_estado' => 1, 'mun_usu_creacion' => 1, 'mun_usu_modificacion' => 1, 'mun_fecha_creacion' => $currentDateTime, 'mun_fecha_modificacion' => $currentDateTime]
        );

        DB::table('mun_municipio')->insert($municipalities);

    }
}